export const Strings = {
  appName: 'Blessed Numbers',
  appTagline: 'Numerology and cultural reflection',

  disclaimer: {
    short: 'For adults 18+ · Cultural reflection only — not gambling, prediction, or financial advice.',
    full: `Blessed Numbers is an entertainment and cultural-reflection app for adults aged 18 and above.\n\nIt offers numerological reflections rooted in the traditions of Singapore and Southeast Asia, drawing from Chinese, Malay, and Indian heritage.\n\nThis app is NOT a gambling product. It is not affiliated with, endorsed by, or related to Singapore Pools, TOTO, 4D, Big Sweep, or any betting operator anywhere in the world. It does not predict winning numbers, contain betting links, or facilitate any form of wager.\n\nAll content is for personal reflection and cultural appreciation only. Nothing in this app is financial advice, a forecast, or a guarantee of any outcome.\n\nNumbers hold personal and cultural significance — their meaning belongs to you to interpret with wisdom and discernment. Always exercise your own judgement in all life decisions.\n\nIf you or someone you know struggles with gambling, free, confidential support is available in Singapore from the National Council on Problem Gambling on 1800-6-668-668.`,
    acknowledgeLabel: 'I am 18 or older and understand this app is for cultural reflection only — not gambling.',
    button: 'I Understand — Begin',
    ageGateError: 'Blessed Numbers is for adults aged 18 and above.',
    ageGateBody: 'You must be 18 or older to use this app. Please return when you reach the required age.',
  },

  onboarding: {
    welcome: {
      title: 'Welcome to\nBlessed Numbers',
      subtitle: 'Discover the cultural wisdom\nand meaning in your numbers',
      feature1: 'Rooted in Chinese, Malay & Indian traditions',
      feature2: 'Thoughtful reflection, not prediction',
      feature3: 'Your numbers, your story',
      cta: 'Get Started',
    },
    profile: {
      title: 'Your Profile',
      subtitle: 'Your name and birth date help us\nderive your personal numbers',
      nameLabel: 'Your Name',
      namePlaceholder: 'e.g. Lim Ah Kow',
      birthdateLabel: 'Date of Birth',
      dayPlaceholder: 'DD',
      monthPlaceholder: 'MM',
      yearPlaceholder: 'YYYY',
      cta: 'Continue',
      errorName: 'Please enter your name.',
      errorDate: 'Please enter a valid date of birth.',
    },
    personalise: {
      title: "Let's personalise your\nblessed numbers",
      subtitle: 'Three small details. Each one shapes the cultural reflection we draw for you.',
      zodiacLabel: 'YOUR CHINESE ZODIAC',
      zodiacHint: 'The animal of your birth year',
      favouriteLabel: 'A NUMBER THAT FEELS BLESSED (OPTIONAL)',
      favouriteHint: '1–49 · the number that has always meant something to you',
      favouritePlaceholder: 'e.g. 8',
      favouriteError: 'Please choose a number between 1 and 49.',
      pantangLabel: 'PANTANG MODE',
      pantangHint: 'Step around numbers you find inauspicious. We will never include them in your readings.',
      avoidLabel: 'NUMBERS TO STEP AROUND',
      avoidHint: 'Tap to add. Tap again to remove.',
      signalLabel: 'WHAT BRINGS YOU HERE TODAY? (OPTIONAL)',
      signalHint: 'A short reflection — a hope, a worry, a moment.',
      signalPlaceholder: 'e.g. A peaceful year for my family',
      signalError: 'Please share a reflection that is not about gambling.',
      cta: 'Continue',
      skip: 'Skip — use defaults',
      footnote: 'For entertainment and cultural reflection only.',
    },
    firstReading: {
      eyebrow: '★ YOUR FIRST READING IS READY',
      title: (name: string) => `${name}, your blessed\nnumbers are waiting.`,
      bodyA: 'Six numbers, drawn from your name and birth month, woven through Chinese, Malay, and Indian numerology.',
      bodyB: "Take a quiet moment. Open the door whenever you're ready.",
      themeLabel: "Today's theme",
      cta: 'Open My First Reading →',
      skip: 'Maybe later',
    },
  },

  paywall: {
    title: 'Unlimited Readings',
    subtitle: 'Read your blessed numbers every day',
    freeLimit: 'Free plan: 1 reading per day',
    feature1: 'Unlimited daily readings',
    feature2: 'Full per-number explanations',
    feature3: 'Save all your readings',
    monthly: 'Monthly',
    monthlyPrice: 'S$4.99 / month',
    annual: 'Annual',
    annualPrice: 'S$39.99 / year',
    annualSave: 'Save 33%',
    ctaMonthly: 'Subscribe Monthly',
    ctaAnnual: 'Subscribe Annually',
    restore: 'Restore Purchases',
    disclaimer: 'Subscriptions auto-renew. Cancel anytime in App Store settings.',
    close: 'Maybe Later',
  },

  home: {
    title: 'Blessed Numbers',
    subtitle: 'What number holds meaning for you?',
    selectType: 'Choose a number type',
    inputLabel: 'Enter your number',
    cta: 'Reveal My Numbers',
    countLabel: 'HOW MANY NUMBERS?',
    intentionLabel: 'YOUR INTENTIONS',
    intentionHint: 'Choose one or more',
    freeReading: '1 free reading today',
    noFreeReadings: 'No free readings left today',
    premiumBadge: 'Unlimited · Premium',
    numberTypes: {
      birthdate: 'Birth Date',
      phone: 'Phone Number',
      house: 'House / Unit Number',
      vehicle: 'Vehicle Plate',
      id: 'Identity Number',
    } as const,
    birthdatePlaceholder: 'DD MM YYYY',
    numberPlaceholder: 'Enter digits',
    dailyExtras: {
      title: "TODAY'S BLESSED PATTERN",
      theme: 'THEME',
      timing: 'BEST TIMING',
      direction: 'AUSPICIOUS DIRECTION',
      avoid: 'NUMBERS TO STEP AROUND',
      premiumLock: 'Unlock with Premium →',
      premiumHint: 'Two more readings revealed for Premium members',
    },
    signal: {
      label: 'A NUMBER YOU NOTICED TODAY',
      hint: 'Optional — fold a 1–49 into today\'s reading.',
      placeholder: '8',
      cta: 'SET',
      savedLabel: "TODAY'S SIGNAL",
      clear: 'Change',
    },
    almanacStrip: {
      eyebrow: "TODAY'S REFLECTION",
      bright: 'Today is a Bright day',
      steady: 'Today is a Steady day',
      gentle: 'Today is a Gentle day',
      cta: 'Read more',
    },
  },

  almanac: {
    title: "Your Luck Today",
    eyebrow: "YOUR LUCK TODAY",
    aiBadge: 'AI POWERED · UPDATED DAILY',
    score: {
      label: 'OVERALL LUCK',
      outOf: 'out of 10',
      summary: "Today's blend",
      lockedHint: 'Unlock your daily luck score',
      lockedCta: 'See My Score →',
    },
    kauCim: {
      title: '1 · Daily Fortune Stick',
      subtitle: 'Kau Cim · 求籤',
      stickLabel: 'STICK',
      ratingLabel: 'RATING',
    },
    zodiac: {
      title: '2 · Daily Animal Luck',
      subtitle: 'Chinese Zodiac · 生肖',
      compatLabel: 'TODAY\'S COMPATIBILITY',
      coloursLabel: 'Lucky colours',
      numbersLabel: 'Lucky numbers',
      rapport: {
        harmonious: 'Harmonious',
        neutral: 'Neutral',
        clashing: 'Take it gently',
      } as const,
    },
    bazi: {
      title: '3 · Element Balance',
      subtitle: 'BaZi Lite · 八字',
      youLabel: 'YOU',
      dayLabel: 'TODAY',
      relationLabels: {
        supports: 'You energise today',
        'is supported': 'Today supports you',
        restrains: 'You shape today',
        'is restrained': 'Be cautious today',
        aligned: 'Aligned with today',
      } as const,
    },
    iching: {
      title: '4 · Hexagram of the Day',
      subtitle: 'I Ching · 易經',
      meaningLabel: 'MEANING',
      adviceLabel: 'ADVICE',
    },
    tongShu: {
      title: '5 · Do & Don\'t Today',
      subtitle: 'Tong Shu · 通書',
      goodFor: 'Good for · 宜',
      avoid: 'Avoid · 忌',
    },
    luckyNumbers: {
      title: 'Today\'s Lucky Numbers',
      subtitle: 'For entertainment · play within your means',
      fourD: '4D',
      toto: 'TOTO',
    },
    fortuneLabel: "Today's saying",
    cta: 'Open My Personal Reading',
    refresh: 'Refreshes each morning, Singapore time',
    entertainmentNote: 'For cultural fun and reflection only. Not a forecast or financial advice.',
  },

  analysis: {
    title: 'Your Number\'s Meaning',
    loading: 'Reflecting on the wisdom of your number…',
    errorGeneric: 'We could not complete your reflection. Please try again.',
    errorSafety: 'This type of query cannot be processed. Please enter a different number.',
    errorNetwork: 'No connection. Please check your network and try again.',
    errorMissingKey: 'AI service is not configured. Create a .env file with EXPO_PUBLIC_GROQ_API_KEY (see .env.example).',
    saveButton: 'Save This Reading',
    savedConfirm: 'Reading saved to your history.',
    newReading: 'New Reading',
  },

  history: {
    title: 'Your Readings',
    empty: 'No saved readings yet.\nYour reflections will appear here.',
    deleteTitle: 'Remove Reading',
    deleteMessage: 'This reading will be removed from your history.',
    deleteConfirm: 'Remove',
    deleteCancel: 'Keep',
  },

  settings: {
    title: 'Settings',
    textSizeSection: 'Text Size',
    textSizeSmall: 'Standard',
    textSizeMedium: 'Large',
    textSizeLarge: 'Extra Large',
    aboutSection: 'About',
    aboutTitle: 'About Blessed Numbers',
    aboutBody:
      'Blessed Numbers offers numerological and cultural reflections drawing from the traditions of Chinese, Malay, and Indian heritage in Singapore and Southeast Asia.\n\nDesigned with care for adults who value cultural wisdom.',
    versionLabel: 'Version',
    disclaimerTitle: 'Full Disclaimer',
    privacyTitle: 'Privacy Policy',
  },

  errors: {
    generic: 'Something went wrong. Please try again.',
    noNetwork: 'No internet connection.',
  },
} as const;

export type NumberType = keyof typeof Strings.home.numberTypes;
